[package]
org = "userportal"
name = "auth_service"
version = "0.1.0"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.12.0"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.12.0"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.7.2"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.9.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.4.0"