[package]
org = "userportal"
name = "auth_service"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "org.xerial"
artifactId = "sqlite-jdbc"
version = "3.42.0.0"

[[platform.java17.dependency]]
groupId = "org.mindrot"
artifactId = "jbcrypt"
version = "0.4"