[userportal.auth_service]
# JWT Configuration
jwtSecret = "your-super-secret-jwt-key-change-in-production-min-32-chars"
jwtExpiryTime = 3600  # 1 hour in seconds
jwtIssuer = "userportal-auth"
jwtAudience = "userportal-users"

# Server Configuration
port = 8080

# Database Configuration (SQLite)
dbPath = "database/userportal.db"